### ISSUE TITLE
Publish job is broken - assets are not uploaded

### ISSUE THREAD

**Issue by Mikescops** [Brooooooklyn/keyring-node#45]
Hello again @Brooooooklyn 😅 

Sounds like the publish job is broken and binaries are not being published properly

<img width="1359" alt="image" src="https://github.com/Brooooooklyn/keyring-node/assets/4266283/48d45b8e-bfda-4bdf-83a8-381ed18c7c86">

https://github.com/Brooooooklyn/keyring-node/actions/runs/8325411210/job/22779283618

**Comment by Mikescops** [comment]
Hey @Brooooooklyn, could you fix the release please 🙏 ?

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/Brooooooklyn/keyring-node/releases/tag/v1.1.5
